@extends('layouts.app')

@section('content')
    @include('partials.hero')
    @include('partials.proyecto')
    @include('partials.respaldo')
    @include('partials.aspiracional')
    @include('partials.modelos')
    @include('partials.precios')
    @include('partials.casa-club')
    @include('partials.zona')
    @include('partials.ubicacion')
    @include('partials.interiores')
    @include('partials.exteriores')
    @include('partials.asesoria')
    @include('partials.brokers')
    @include('partials.cta-final')
@endsection
